<?php
return [
    // TODO it could have been simpler, in one line
    // urls work irritating now. autogenerated index.php and other garbage. ignore.
    '/' => 'news/home',
        'login' => 'site/login',
        'registration' => 'site/registration-form',
        'send-registration-form' => 'site/registration-send',
        'logout' => 'site/logout',
        'a-list-of-news' => 'news/home',
        'fill-in-a-new-news-item' => 'news/a-new-news-item-form',
        'a-look-at-a-specific-news-item/<news_item_id:\d+>' => 'news/news-item',
        'like-news-item' => 'news/like-news-item',
];
