<?php
return [
    // TODO it could have been simpler, in one line
    // urls work irritating now. autogenerated index.php and other garbage. ignore.
    [
        'pattern' => '/',
        'route' => 'news/home',
        'encodeParams' => false
    ],
    [
        'pattern' => 'login',
        'route' => 'site/login',
        'encodeParams' => false
    ],
    [
        'pattern' => 'logout',
        'route' => 'site/logout',
        'encodeParams' => false
    ],
    [
        'pattern' => 'a-list-of-news',
        'route' => 'news/home',
        'encodeParams' => false
    ],
    [
        'pattern' => 'create-a-new-news-item',
        'route' => 'news/create',
        'encodeParams' => false
    ],
    [
        'pattern' => 'a-look-at-a-specific-news-item/<news_item_id:\d+>',
        'route' => 'news/newsitem', // TODO how to specify news id restriction
        'encodeParams' => false
    ]
];
