<?php
return [
    // TODO it could have been simpler, in one line
    // urls work irritating now. autogenerated index.php and other garbage. ignore.
    [
        'pattern' => '/',
        'route' => 'news/home',
        'encodeParams' => false
    ],
    [
        'pattern' => 'login',
        'route' => 'site/login',
        'encodeParams' => false
    ],
    [
        'pattern' => 'logout',
        'route' => 'site/logout',
        'encodeParams' => false
    ],
    [
        'pattern' => 'a-list-of-news/<tags><order_by><page_number:\d+>',
        'route' => 'news/home',
        'encodeParams' => true
    ],
    [
        'pattern' => 'fill-in-a-new-news-item',
        'route' => 'news/a-new-news-item-form',
        'encodeParams' => false
    ],
    [
        'pattern' => 'a-look-at-a-specific-news-item/<news_item_id:\d+>',
        'route' => 'news/news-item',
        'encodeParams' => false
    ],
    [
        'pattern' => 'like-news-item',
        'route' => 'news/like-news-item',
    ],
    // TODO delete
    'test' => 'news/test'
];
